# Generated by Django 3.1.4 on 2020-12-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_Description', models.CharField(max_length=300)),
                ('worker_id', models.IntegerField(null=True)),
                ('recruter_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Worker_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('category_1', models.CharField(max_length=255)),
                ('category_1_vc', models.CharField(max_length=255)),
                ('category_1_exp', models.IntegerField()),
                ('category_2', models.CharField(max_length=255)),
                ('category_2_vc', models.CharField(max_length=255)),
                ('category_2_exp', models.IntegerField()),
                ('category_3', models.CharField(max_length=255)),
                ('category_3_vc', models.CharField(max_length=255)),
                ('category_3_exp', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
