# Generated by Django 3.1.4 on 2020-12-18 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201218_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='recruter_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='worker_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_1_exp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_1_vc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_2_exp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_2_vc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_3_exp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='category_3_vc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
