# Generated by Django 3.1.4 on 2020-12-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20201218_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smartphone',
            field=models.BooleanField(default=True),
        ),
    ]
