# Generated by Django 3.1.4 on 2020-12-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_user_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='amount',
            field=models.IntegerField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_details',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
