# Generated by Django 3.1.4 on 2020-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20201219_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='worker_id',
            field=models.IntegerField(null=True),
        ),
    ]
