# Generated by Django 3.1.4 on 2020-12-19 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20201219_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_details',
            name='status',
        ),
        migrations.CreateModel(
            name='WorkersJobRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.job_details')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitersJobRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('worker_id', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.job_details')),
            ],
        ),
    ]
