# Generated by Django 3.1.4 on 2020-12-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20201219_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workersjobrequests',
            name='job_id',
        ),
        migrations.RenameField(
            model_name='job_details',
            old_name='recruter_id',
            new_name='recruiter_id',
        ),
        migrations.AlterField(
            model_name='job_details',
            name='worker_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='authapp.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecruitersJobRequests',
        ),
        migrations.DeleteModel(
            name='WorkersJobRequests',
        ),
    ]
