# Generated by Django 3.1.4 on 2020-12-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20201219_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_details',
            old_name='recruiter_id',
            new_name='recruiter',
        ),
    ]
