# Generated by Django 3.1.4 on 2020-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20201219_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_details',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
