# Generated by Django 3.1.4 on 2020-12-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20201219_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_details',
            name='worker',
        ),
        migrations.AddField(
            model_name='job_details',
            name='worker_id',
            field=models.IntegerField(null=True),
        ),
    ]
