# Generated by Django 3.1.4 on 2020-12-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20201220_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authapp.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
