# Generated by Django 3.1.4 on 2020-12-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20201220_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recruitersrequests',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workersrequests',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
