# Generated by Django 3.1.4 on 2020-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_recruitersrequests_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersrequests',
            name='recruiter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
