# Generated by Django 3.1.4 on 2020-12-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_auto_20201222_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='isVerified',
        ),
    ]
